### ISSUE TITLE
Archive deployment

### ISSUE THREAD

**Issue by sveetch** [sveetch/django-icomoon#2]
A really usefull feature would be a command line action to automatically deploy stuff from download webfont archive on Icomoon.

So the CLI action should take a path to the zip archive then open it (in temporary dir), put the manifest and font files to the right directory, then finally generate the scss file which contains the icon map.

**Comment by slothyrulez** [comment]
+1

**Comment by sveetch** [comment]
Done since 0.3.0 (commit 20dedea)
